src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>test</fullName>
        <active>true</active>
        <label>test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/encrypt_Config__c.object
<CustomObject>
    <label>encrypt Config</label>
    <nameField>
        <displayFormat>E-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>encrypt Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/encryptionobj__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>key__c</fullName>
        <label>key_32</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>encryptionsetting</label>
</CustomObject>

src/classes/TestEncryptController.cls
@isTest(SeeAllData=true)
public class TestEncryptController{
      public static testMethod void TestEncryptDecrypt(){
      
      Test.startTest();      
      Test.setCurrentPage(Page.encryption);
      encryptionobj__c settings= encryptionobj__c.getOrgDefaults();
      encrypt_Config__c objEncrConf = new encrypt_Config__c();
      encryptController objEncryptController = new encryptController();
      
      //objEncryptController.seckey = Blob.valueof(settings.key__c);
      objEncryptController.run();
      
      objEncryptController.objectval = 'Account'; 
      objEncryptController.getFieldss();
      objEncryptController.getFieldss2();
      objEncryptController.fieldval = 'name';
      objEncryptController.encrypt();
      objEncryptController.decrypt();
      objEncryptController.testfunction();
      
      Test.stopTest();
  }

}