src/objects/License_Usage__c.object
<CustomObject>
    <fields>
        <fullName>AvailableLicenses__c</fullName>
        <label>Available Licenses</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LicenseName__c</fullName>
        <label>License Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LicenseType__c</fullName>
        <label>LicenseType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgID__c</fullName>
        <label>OrgID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgName__c</fullName>
        <label>OrgName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TotalLicenses__c</fullName>
        <label>Total Licenses</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UsedLicenses__c</fullName>
        <label>Used Licenses</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>License Usage</label>
    <nameField>
        <label>License Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses Usage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GetLicenses.cls
@RestResource(urlMapping='/LicenseUtilization/*')

global with sharing class GetLicenses{

@HttpPost
global static void doPost(List<License> Licenses){
    List<License_Usage__c> newLicenses = new List<License_Usage__c>();
    List<License_Usage__c> oldLicenses = new List<License_Usage__c>();
    for(License l:Licenses)
    {
        License_Usage__c lu = new License_Usage__c();
        lu.OrgName__c = l.OrgName;
        lu.OrgID__c = l.OrgID;
        lu.LicenseType__c = l.LicenseType;
        lu.LicenseName__c = l.Name;
        lu.Status__c = l.Status;
        lu.TotalLicenses__c = l.TotalLicenses;
        lu.UsedLicenses__c = l.UsedLicenses;
        lu.AvailableLicenses__c = l.AvailableLicenses;
        newLicenses.add(lu);
    }
    oldLicenses = [select id from License_Usage__c where OrgID__c = :newLicenses[0].OrgID__c];
    delete oldLicenses;
    insert newLicenses;
}


global class License{
    String OrgName;
    String OrgID;
    String LicenseType;
    String Name;
    String Status;
    Decimal TotalLicenses;
    Decimal UsedLicenses;
    Decimal AvailableLicenses;
}

}